name: Node Fullstack CI/CD

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    # Backend
    - name: Install Backend Dependencies
      run: |
        cd app/backend
        npm install

    - name: Run Backend
      run: |
        cd app/backend
        node server.js &

    # Frontend check
    - name: Check Frontend
      run: ls app/frontend

    - name: Success Message
      run: echo "Pipeline executed successfully"
