name: Server Setup

on:
  workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to EC2 and Install Software
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Connected to server ✅"
            whoami
            hostname

            echo "Updating system..."
            sudo apt update -y

            echo "Installing Nginx..."
            sudo apt install nginx -y

            echo "Installing Git..."
            sudo apt install git -y

            echo "Installing Node.js..."
            sudo apt install nodejs npm -y

            echo "Installing PM2..."
            sudo npm install -g pm2

            echo "Starting Nginx..."
            sudo systemctl start nginx
            sudo systemctl enable nginx

            echo "Checking Nginx status..."
            sudo systemctl status nginx

            echo "Server setup completed successfully 🎉"
